export const btnConstants = {
  ok: 'Ok',
  cancel: 'Cancel',
  complete: 'Complete',
  login: 'Login',
  logout: 'Logout',
  deleteAccount: 'Delete Account',
  signup: 'Sign up',
  verify: 'Verify',
  continue: 'Continue',
  update: 'Update',
  next: 'Next',
  save: 'Save',
  submit: 'Submit',
  skip: 'Skip',
  post: 'Post',
  register: 'Register',
  aboutUs: 'About Us',
  loginWith: 'Log in with',
  enterOtp: 'Enter Verification Code',
  resendOtp: 'Resend OTP',
  sendMessage: 'Send Message',
  notifications: 'Notifications',
  alreadyAccount: 'Already have an account?',
  noAccount: 'Don’t have an account?',
  forgotPassword: 'Forgot Password?',
  contactUs: 'Contact Us',
  watchFB: 'Watch On Facebook',
  send: 'Send',
  create: 'Create',
  yes: 'Yes',
  no: 'No',
  upcoming: 'Upcoming',
  past: 'Past',
  viewDetails: 'View Details',
  cancelTrip: 'Cancel Trip',
  rateVendor: 'Rate Our Vendor',
  rateTrip: 'Rate A Trip',
  viewQuote: 'View Quote',
  reserveNow: 'Reserve Now',
  modificationPolicy: 'Modification Policy & Cancellation',
  getQuote: 'Get A Quote',
  back: 'Back',
  viewReservation: 'View Reservation',
};

export const constants = {
  mobileNumber: 'Mobile Number',
  orLoginWith: 'Or Login with',
  createProfile: 'Create Profile',
  enterVerificationCode: 'Enter Verification Code',
  dontReceiveOtp: "Din't receive the OTP?",
  backToLoginScreen: 'Back to Login',
  goBack: 'Go Back',
  sendAgain: 'Send Again',
  firstName: 'First Name',
  lastName: 'Last Name',
  email: 'Email',
  mobile: 'Mobile',
  one: '1',
  two: '2',
  three: '3',
  oneWay: 'ONE WAY',
  roundTrip: 'ROUND TRIP',
  pickup: 'Pickup',
  drop: 'Drop',
  pickupLocationHeading: 'Pickup Location',
  pickupLocation: 'Pickup Location: ',
  pickupDate: 'Pickup Date',
  pickupTime: 'Pickup Time',
  stopDate: 'Stop Date',
  stopTime: 'Stop Time',
  stopLocationHeading: 'Stop Location',
  stopPickupLocation: 'Stop Pickup Location: ',
  pickupDateTime: 'Pickup Date & Time: ',
  addStop: 'Add a Stop',
  removeStop: 'Remove Stop',
  hrs: 'hours',
  mins: 'minutes',
  stop: 'Stop',
  stopLocation: 'Stop Location: ',
  keepVehicle: 'Keep Vehicle on site',
  dropoff: 'Dropoff',
  dropoffLocation: 'Dropoff Location',
  dropLocation: 'Drop Location: ',
  dropLocationHeading: 'Drop Location',
  currentLocation: 'Current Location',
  buildAQuote: 'Build a Quote',
  getQuote: "Let's Get Your Quote,",
  journeyPlanning: 'What type of journey are you planning?',
  plannedRoute: "What's your planned route, ",
  startItinerary: 'Start by adding your itinerary',
  travelTime: 'Travel Time: ',
  totalTravelTime: 'Total Travel Time: ',
  searchLocation: 'Search Location',
  numberOfPassengers: 'Number of Passengers',
  eventType: 'Event Type',
  giveTripName: 'Give Your Trip A Name',
  totalTravelTimeHeading: 'Total Travel Time',
  pickupAt: 'Pickup At ',
  dropoffAt: 'Dropoff At ',
  am: 'Am',
  pm: 'PM',
  selectVehicle: 'Select Vehicle',
  luxuryCoach: 'LUXURY COACH',
  sar: 'SAR',
  minusSar: '-SAR',
  luxuryCoachDesc:
    'A luxurious coach with comfortable seating and premium amenities',
  getTheQuote: 'Get The Quote',
  quotes: 'Quotes',
  quoteId: 'Quote ID: ',
  quoteDetails: 'Quote Details',
  quoteOn: 'Quote On: ',
  itinerary: 'Itinerary',
  bookingName: 'Booking Name: ',
  quoteStatus: 'Quote Status: ',
  acceptUnconfirmed: 'Accepted & Unconfirmed',
  viewQuote: 'View Quote: ',
  reservations: 'Reservations',
  chat: 'Chat',
  account: 'Account',
  quoteOverview: 'Quote Overview',
  applyCouponCode: 'Apply Coupon Code',
  couponTitle: 'Coupon Title: ',
  apply: 'Apply',
  applied: 'Applied',
  benefits: 'Benefits: ',
  termsConditions: 'Terms & Conditions',
  viewMore: 'View More',
  viewLess: 'View Less',
  fareCalculationHeading: 'Fare calculation',
  totalBaseFare: 'Total Base Fare (Hourly)',
  couponDiscount: 'Coupon Discount',
  locationToPickupLocationExtra: 'Location To Pickup Location (Extra)',
  appCharges: 'Application charges',
  totalFare: 'Total Fare',
  modificationPolicy: 'Modification Policy',
  reservationId: 'Reservation ID: ',
  customerId: 'Customer ID: ',
  vendorVehicleDetails: 'Vendor & Vehicle Details',
  vendorDetails: 'Vendor Details',
  vendorRating: 'Vendor Rating: ',
  totalPassengers: 'Total Passengers: ',
  vehichleDesc: 'Vehichle Description: ',
  vehicleAmenities: 'Vehicle Amenities: ',
  driverDetails: "Driver's Details: ",
  driverVehicleDetails: 'Driver & Vehicle Details',
  driverName: 'Driver Name: ',
  phoneNumber: 'Phone Number: ',
  phoneNumberHeading: 'Phone Number',
  status: 'Status: ',
  reservationDetails: 'Reservation Details',
  driverInfo: 'Driver Info',
  vehicleCategory: 'Vehicle Category: ',
  manageDocuments: 'Manage Documents',
  helpSupport: 'Help & Support',
  customerCareNumber: 'Customer Care Number: ',
  viewInvoice: 'View Invoice',
  rating: 'Rating',
  logoutDesc: 'Are you sure you want to logout?',
  deleteDesc: 'Are you sure you want to delete account?',
  ratingQuestiion: 'How Would you rate our Vendor Experience?',
  tripExperienceQuestion: 'How would you rate your trip experience?',
  cancelTrip: 'Cancel Trip',
  cancelReason: 'Reason of Cancellation',
  description: 'Description',
  myProfile: 'My Profile',
  notifications: 'Notifications',
  customerSupport: 'Customer Support',
  aboutUs: 'About Us',
  termsAndConditions: 'Terms and Conditions',
  termsAndConditionsCoupon: 'Terms and Conditions: ',
  privacyPolicy: 'Privacy Policy',
  logout: 'Logout',
  deleteAccount: 'Delete Account',
  pastMessages: 'Past Messages',
  moreMessages: 'More Messages',
  locationDetails: 'Location Details',
  writeMessage: 'Write a Message',
  today: 'Today',
  vendorName: 'Vendor: ',
  vehichles: 'Vehicles: ',
  vehicleName: 'Vehicle: ',
  occupancy: 'Occupancy: ',
  liveTracking: 'Live Tracking',
  thankYou: 'Thank You!',
  paymentDone: 'Payment Done Successfully',
  error: 'Error!',
  paymentFailed: 'Payment Failed',
  activeNow: 'Active Now',
  ringing: 'Ringing...',
  incoming: 'Incoming...',
  noChatFound: 'No Chats Found!',
  noDataFound: 'No Data Found!',
  admin: 'Admin',
};

export const dummyText = 'Lorem Ipsum is dummy text.';
export const dummyText2 =
  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry.";

export const dummyText1 =
  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry.";
